import json

from dm_agent.tools import task_complete
from dm_agent.tools.code_analysis_tools import get_code_metrics, get_function_signature, parse_ast
from dm_agent.tools.execution_tools import run_python
from dm_agent.tools.file_tools import create_file, edit_file, read_file, search_in_file


def test_file_tools_create_read_edit_and_search(tmp_path):
    target = tmp_path / "sample.py"

    create_file(
        {
            "path": str(target),
            "content": "def greet():\n    return 'hello'\n",
        }
    )

    assert target.read_text(encoding="utf-8") == "def greet():\n    return 'hello'\n"
    assert read_file({"path": str(target), "line_start": 1, "line_end": 1}) == "def greet():"

    edit_file(
        {
            "path": str(target),
            "operation": "replace",
            "line_start": 2,
            "line_end": 2,
            "content": "    return 'hi'",
        }
    )
    assert "return 'hi'" in target.read_text(encoding="utf-8")

    edit_file(
        {
            "path": str(target),
            "operation": "insert",
            "line_start": 1,
            "content": "# generated by test",
        }
    )

    search_result = search_in_file({"path": str(target), "pattern": "return", "context_lines": 1})
    assert "return 'hi'" in search_result
    assert ">>>" in search_result


def test_code_analysis_tools_return_structured_json(tmp_path):
    module = tmp_path / "module.py"
    module.write_text(
        "import os\n\n"
        "class Greeter:\n"
        "    def greet(self, name: str) -> str:\n"
        "        return f'hello {name}'\n\n"
        "def add(left: int, right: int) -> int:\n"
        "    return left + right\n",
        encoding="utf-8",
    )

    ast_data = json.loads(parse_ast({"path": str(module)}))
    assert ast_data["imports"][0]["module"] == "os"
    assert ast_data["classes"][0]["name"] == "Greeter"
    assert any(func["name"] == "add" for func in ast_data["functions"])

    signature = json.loads(get_function_signature({"path": str(module), "function_name": "add"}))
    assert signature["signature"] == "def add(left: int, right: int) -> int"

    metrics = json.loads(get_code_metrics({"path": str(module)}))
    assert metrics["num_functions"] == 2
    assert metrics["num_classes"] == 1


def test_run_python_executes_inline_code():
    result = run_python({"code": "print('agent-ready')"})
    assert "agent-ready" in result
    assert "returncode: 0" in result


def test_task_complete_accepts_message():
    result = task_complete({"message": "ready"})
    assert "ready" in result


def test_run_python_accepts_script_args(tmp_path):
    script = tmp_path / "echo_args.py"
    script.write_text(
        "import sys\nprint('|'.join(sys.argv[1:]))\n",
        encoding="utf-8",
    )

    result = run_python({"path": str(script), "args": ["left", "right"]})
    assert "left|right" in result
    assert "returncode: 0" in result
